#! /bin/sh
### BEGIN INIT INFO
# Provides:          nightskyboot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start NightSkyTFT on boot
# Description:       Start NightSkyTFT at boot time.
### END INIT INFO

# Author: Tnever 
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

USER=root
HOME=/root

export USER HOME

case "$1" in
  start)
	echo "Starting Night Sky TFT"
	cd /home/pi/NightSkyTFT/
	python /home/pi/NightSkyTFT/NightSkyTFTMain.py
	;;
  stop)
	echo "Stopping Night Sky TFT"
	;;
  *)
	echo "Usage: /etc/init.d/nightskyboot"
	exit 1
	;;
esac

exit 0
